### PR TITLE
Conference papers and posters working

### PR DESCRIPTION
**Pull request by zhongh**
Working for both conference papers and posters. Feel it's ready to go.

### CODE REVIEW

**Comment by mrpatrickwest** [comment]
Is this on dco.tw yet?

**Comment by zhongh** [comment]
This is not on dco.tw yet. The one on dco.tw only has the author formatting

**Comment by zhongh** [comment]
And now it is on.
@mrpatrickwest @zednis 
Please review the change by checking https://dco.tw.rpi.edu/vivo/publications, whose citation service is set to dco.tw.rpi.edu/citation/ which have the changes from this pull request, too.

**Comment by mrpatrickwest** [comment]
Are we sure that that is the proper format for conference papers and posters? This is what I found online: https://www.citethisforme.com/guides/pnas/how-to-cite-a-conference-proceedings

**Comment by zhongh** [comment]
This is due to data-incompleteness in vivo. When a paper is "presentedAt" some conference, usually it will also be "publishedIn" some relevant proceedings of that particular conference. But most of the conference papers/posters registered in vivo are not companied by that publishing information, therefore elastic search could only grab "presentedAt" info.

**Comment by mrpatrickwest** [comment]
👍 

@zednis what do you think? Ready to ship?

**Comment by zednis** [comment]
looks good to me.  :shipit:

**Comment by mrpatrickwest** [comment]
:shipit:

**Pull request merged**
