### PR TITLE
Remove the /php directory and rename api.php to citation.php

### LINKED ISSUE #4: eliminate the php directory
Don't need another level for the scripts. Just put it under dco-citation

### LINKED ISSUE #5: change name from api.php to citation.php
After we close the two pull requests

### PR DESCRIPTION
**Pull request by zhongh**
Fixed #4 and fixed #5

### CODE REVIEW

**Comment by zhongh** [comment]
@mrpatrickwest Go?

**Comment by mrpatrickwest** [comment]
Did you fix .htaccess to go to citation.php instead of api.php?

**Comment by mrpatrickwest** [comment]
Also, change api.php to citation.php on dco.tw and test again

**Comment by zhongh** [comment]
And I have made changes to citation.php and .htaccess on dco.tw and things work as normal.
Good to go? @mrpatrickwest

**Comment by mrpatrickwest** [comment]
what changes did you make? Which branch? Not this one, I hope!!!

**Comment by zhongh** [comment]
@mrpatrickwest It's the change in the commit above 807fc92. Since we changed the name from api.php to citation.php.. So I make a one line change there in .htaccess

**Comment by mrpatrickwest** [comment]
ah ... that change. Thanks for clarifying

Are the changes in /var/www/html yet on dco.tw?

**Comment by zhongh** [comment]
Yep, like this:
https://dco.tw.rpi.edu/citation/11121/3524-1246-5132-9229-CC
will be actually rewritten to:
https://dco.tw.rpi.edu/citation.php?get_citation=11121/3524-1246-5132-9229-CC

**Comment by mrpatrickwest** [comment]
:shipit:

**Pull request merged**
