### PR TITLE
The servive now generates a PNAS citation

### PR DESCRIPTION
**Pull request by mrpatrickwest**
Given a DCO-ID we generate a citation in the PNAS format

### CODE REVIEW

**Comment by zhongh** [comment]
@mrpatrickwest Here is a formatting suggestion. For instance, in citation 

```
Ma, X, Fox, P, (2014) A Jigsaw Puzzle Layer Cake of Spatial Data. Eos, Transactions of the American Geophysical Union 95(19):161-161
```

According to what I studied on PNAS format, the last name and first/middle name initials should be separated just by a space, like ``Ma X, Fox P'', while comma is for separation between author names.
If you want I can go ahead and make the change.

**Comment by mrpatrickwest** [comment]
Sure … go ahead. It’s on dco.tw and in /data/dco/dco-citations

**Comment by zhongh** [comment]
@mrpatrickwest 
For journal articles it seems working
[https://dco.tw.rpi.edu/citation/11121/3524-1246-5132-9229-CC]
[https://dco.tw.rpi.edu/citation/11121/9204-1847-2089-2719-CC]
[https://dco.tw.rpi.edu/citation/11121/4279-7047-5277-6456-CC]
Things like a book or a conference paper could give errors or incomplete information:
[https://dco.tw.rpi.edu/citation/11121/6755-1784-2925-4129-CC]
[https://dco.tw.rpi.edu/citation/11121/3706-4798-8080-7495-CC]
They don't give information in the publication source most likely because the publicationVenue is limited journals.
Maybe we can create an issue to refine the scope and provide error checking.

**Comment by zhongh** [comment]
[http://library.williams.edu/citing/styles/apa.php]
Publications could be books, chapters, etc
We need to refine the scopes and make sure every kind of things will work accordingly

**Comment by mrpatrickwest** [comment]
I say we :shipit: , create an issue to get books working, and whatever other type of document we'll want to generate a citation. What do you think?

**Comment by zhongh** [comment]
I say :shipit: since this pull request has fulfilled its mission.

**Pull request merged**
