### PR TITLE
Using elasticsearch query instead of sparql

### PR DESCRIPTION
**Pull request by mrpatrickwest**

### CODE REVIEW

**Comment by mrpatrickwest** [comment]
on test: https://dco.tw.rpi.edu/vivo/publications

**Comment by mrpatrickwest** [comment]
@zednis wondering if we want to go with elasticsearch or stick with sparql. With elasticsearch it returns 1-2 seconds, sparql query 3-4 seconds.

**Comment by zednis** [comment]
Why is there any delay with elasticsearch?  The content should already be loaded.

**Comment by zednis** [comment]
Ah, I thought you were going to update the JS in publications.html to use content in the elasticsearch search results to generate the citation.  In that case an external citations service would not need to be called - we would have to update the publications ingest process to include the missing fields.

**Comment by zednis** [comment]
counter proposal - create a JS function in publications.html that generates the citation text.

**Comment by mrpatrickwest** [comment]
Eventually the service will be used to generate other citation formats, not just PNAS. So it'll take an additional argument, the citation type. Right now we're just generating PNAS.

So instead of writing a bunch of JavaScript code to take into account the different types of publications and the different citation formats I feel that it would be better to keep it in a service.

**Comment by zednis** [comment]
OK, I am not arguing that we drop the citation service, but we could make the citation text response in the faceted browser effectively lag free by putting a small (and it would be small) amount of JS in publications.html

**Comment by mrpatrickwest** [comment]
In one of your earlier comments you stated that if we added the javascript to publications.html then we wouldn't need to call out to the citation service. How do we generate the citation if we don't either call out to the service or write a lot of javascript code to run the query, determine the type of document and the citation format, then generate the appropriate citation. I do believe I am missing something.

**Comment by zednis** [comment]
Why would it need to run any additional queries?  It would already have all the publication information it needed from the original query of ES that is used to build the result set.  All of the information needed to generate a citation is already in the result set _source object.

```
{
    "total" : 1590,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "dco",
      "_type" : "publication",
      "_id" : "1015-6779-1645-7537-CC",
      "_score" : 1.0,
      "_source":{"uri": "http://info.deepcarbon.net/individual/41c11cff-4774-4c67-b117-6b24188733bf", "publicationYear": "2010", "title": "Archaeoglobus sulfaticallidus sp. nov., a thermophilic and facultatively lithoautotrophic sulfate-reducer isolated from black rust exposed to hot ridge flank crustal fluids", "isDcoPublication": true, "mostSpecificType": "Journal Article", "dcoId": "11121/1015-6779-1645-7537-CC", "volume": "60", "authors": [{"uri": "http://info.deepcarbon.net/individual/5438a34b-2805-4fe4-9868-e6fbe6eabd0f", "name": "Steinsbu, B. O.", "rank": 1}, {"uri": "http://info.deepcarbon.net/individual/40d0d86e-c8fb-499a-a6c1-523cba6a1860", "name": "Thorseth, I. H.", "rank": 2}, {"uri": "http://info.deepcarbon.net/individual/c4f5d7f1-2cbf-4eff-8e42-d109ff776cf6", "name": "Nakagawa, Satoshi", "rank": 3}, {"uri": "http://info.deepcarbon.net/individual/n1486", "name": "Inagaki, Fumio ", "rank": 4, "researchArea": ["Geomicrobiology", "Geobiotechnology"]}, {"uri": "http://info.deepcarbon.net/individual/d7915d3c5-c216-11e3-89f2-c8e0eb162b4f", "name": "Lever, Mark", "rank": 5, "researchArea": ["Geomicrobiology", "Microbial Ecology", "microbial energetics", "oceanic crustal microbiology", "Sediment microbiology"]}, {"uri": "http://info.deepcarbon.net/individual/8ddc5f9f-36ef-4083-9a62-c249351faacb", "name": "Engelen, Bert", "rank": 6, "researchArea": ["Sediment microbiology", "Microbial Physiology", "Benthic phages"]}, {"uri": "http://info.deepcarbon.net/individual/18e5f5ba-10e3-47ac-b6de-2df6b9a3cc1b", "name": "Ovreas, L.", "rank": 7}, {"uri": "http://info.deepcarbon.net/individual/3223e203-fe7c-4693-89af-94dc7ee43732", "name": "Pedersen, R. B.", "rank": 8}], "issue": "12", "pageStart": "2745", "publishedIn": {"uri": "http://info.deepcarbon.net/individual/b0d1124d-4fab-4048-babf-88d6dd6bdf37", "name": "INTERNATIONAL JOURNAL OF SYSTEMATIC AND EVOLUTIONARY MICROBIOLOGY"}, "community": {"uri": "http://info.deepcarbon.net/individual/d4bc62ea2-aa8e-4789-9838-ce445dae9a78", "name": "Deep Life Community"}, "pageEnd": "2752", "doi": "10.1099/ijs.0.016105-0"}
    }
```

edit: all we have to do is implement a JS function that generates citation text from the publication obj and call it from the handlebar template

template:

```
{{#if dcoId}}<a id="{{id dcoId}}" dcoid="{{dcoId}}" href="#na" data-toggle="popover" data-trigger="manual" title="Recommended Citation" data-content="{{citationText}}" onclick="invokePopover(this)" popover-status="off"><img class="badge" src="{{citationBadgeURL}}"/></a>{{/if}}
```

JS:

```
Handlebars.registerHelper('citationText', function(source) {
            var publication = source["data"]["root"]
            <!-- read publication object, generate citation -->
            return "";
        });
```

**Pull request merged**
