### PR TITLE
URL rewriting works

### LINKED ISSUE #1: URL rewriting is not working
@zednis @mrpatrickwest Use DCO-ID "11121/3524-1246-5132-9229-CC" for our example.

`http://localhost/api.php?get_citation=11121/3524-1246-5132-9229-CC` will successfully return some information on the DCO-ID provided

I want to, by setting rewriting rules in `.htaccess` file, have a url rewriting such that 
`http://localhost/citation/11121/3524-1246-5132-9229-CC` will be rerouted to the original URL and yield the same result.

Currently I set in `.htaccess``  like this below, but nothing is working (URL Not Found).

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule ^citation/([a-zA-Z0-9/-]+)$ api.php?get_citation=$1
</IfModule>
```

### PR DESCRIPTION
**Pull request by zhongh**
`http://localhost/citation/11121/3524-1246-5132-9229-CC` will lead to:
image

Fixed #1

### CODE REVIEW

**Comment by mrpatrickwest** [comment]
Change api.php to citation.php since it's specific to citations

**Comment by mrpatrickwest** [comment]
Is there a reason why there's a php directory?

**Comment by zhongh** [comment]
The php directory has no reason to exist and has been eliminated. `api.php` is renamed to `citation.php` with according changes to the rewrite rule. 
Fixed #5 and fixed #4 
Ready to go?

**Comment by mrpatrickwest** [comment]
Bugger ... since there's still one more pull request out there there's going to be conflicts. We'll have to work those out.

**Comment by zhongh** [comment]
@mrpatrickwest Sorry! I will revert this commit!

**Comment by zhongh** [comment]
@mrpatrickwest Just reverted that commit. Yes exactly. Good to go?

**Comment by mrpatrickwest** [comment]
:shipit:

**Pull request merged**
